version: "3.8"

services:
  app:
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npx nodemon index.js
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=technical_test
      - MYSQL_PASSWORD=root
      - MYSQL_USER=dubon
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080